import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Facebook, X } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: "#F3F2EC" }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>This is the header section</header>
        <div className="w-full min-h-[80vh]">{children}</div>
        <footer className="py-14 border-t border-t-[#E0E0E0]">
          <div>
            <div className="text-center max-w-screen-lg mx-auto mb-4">
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
              <a href="#" className="uppercase">
                Magazine
              </a>
              <span color="#2a2a2a">&nbsp; |&nbsp;&nbsp;</span>
            </div>
            <p className="text-center mb-4">
              <span className="block">ISSN 2689-2715 | Online</span>
              <span className="block">​ISSN 2688-5425 ​| Print</span>
              <span className="block">Bookverse REVIEW | © COPYRIGHT 2024</span>
              <span className="block">​ALL RIGHTS RESERVED.</span>
            </p>
            <div className="text-center">
              <p className="mb-4">FOLLOW US</p>
              <div className="flex items-center justify-center gap-2">
                <Facebook />
                <X />
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
